# Generated by Django 5.1.3 on 2024-11-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_claim_claimdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='payment_status',
            field=models.CharField(default='Unpaid', max_length=20),
        ),
    ]
