# Generated by Django 5.1.3 on 2024-11-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_claim_payment_date_claim_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrecord',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policyrecord',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
